package com.yan.common.user.model;

import java.io.Serializable;
import java.util.Date;

public class SysUser extends SysUserKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_NAME
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_PASSWORD
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ADDRESS
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_EMAIL
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_PHONE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_BIRTHDAY
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_JOINDATE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private Date userJoindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_PHOTO
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_TYPE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_VALID
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private Short userValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_HOSP
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userHosp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_DEPT
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private String userDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_NAME
     *
     * @return the value of sys_user.USER_NAME
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_NAME
     *
     * @param userName the value for sys_user.USER_NAME
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_PASSWORD
     *
     * @return the value of sys_user.USER_PASSWORD
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_PASSWORD
     *
     * @param userPassword the value for sys_user.USER_PASSWORD
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_ADDRESS
     *
     * @return the value of sys_user.USER_ADDRESS
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_ADDRESS
     *
     * @param userAddress the value for sys_user.USER_ADDRESS
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_EMAIL
     *
     * @return the value of sys_user.USER_EMAIL
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_EMAIL
     *
     * @param userEmail the value for sys_user.USER_EMAIL
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_PHONE
     *
     * @return the value of sys_user.USER_PHONE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_PHONE
     *
     * @param userPhone the value for sys_user.USER_PHONE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_BIRTHDAY
     *
     * @return the value of sys_user.USER_BIRTHDAY
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_BIRTHDAY
     *
     * @param userBirthday the value for sys_user.USER_BIRTHDAY
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_JOINDATE
     *
     * @return the value of sys_user.USER_JOINDATE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public Date getUserJoindate() {
        return userJoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_JOINDATE
     *
     * @param userJoindate the value for sys_user.USER_JOINDATE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserJoindate(Date userJoindate) {
        this.userJoindate = userJoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_PHOTO
     *
     * @return the value of sys_user.USER_PHOTO
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserPhoto() {
        return userPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_PHOTO
     *
     * @param userPhoto the value for sys_user.USER_PHOTO
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto == null ? null : userPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_TYPE
     *
     * @return the value of sys_user.USER_TYPE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_TYPE
     *
     * @param userType the value for sys_user.USER_TYPE
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_VALID
     *
     * @return the value of sys_user.USER_VALID
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public Short getUserValid() {
        return userValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_VALID
     *
     * @param userValid the value for sys_user.USER_VALID
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserValid(Short userValid) {
        this.userValid = userValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_HOSP
     *
     * @return the value of sys_user.USER_HOSP
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserHosp() {
        return userHosp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_HOSP
     *
     * @param userHosp the value for sys_user.USER_HOSP
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserHosp(String userHosp) {
        this.userHosp = userHosp == null ? null : userHosp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_DEPT
     *
     * @return the value of sys_user.USER_DEPT
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public String getUserDept() {
        return userDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_DEPT
     *
     * @param userDept the value for sys_user.USER_DEPT
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    public void setUserDept(String userDept) {
        this.userDept = userDept == null ? null : userDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Aug 01 14:00:05 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", userPassword=").append(userPassword);
        sb.append(", userAddress=").append(userAddress);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userBirthday=").append(userBirthday);
        sb.append(", userJoindate=").append(userJoindate);
        sb.append(", userPhoto=").append(userPhoto);
        sb.append(", userType=").append(userType);
        sb.append(", userValid=").append(userValid);
        sb.append(", userHosp=").append(userHosp);
        sb.append(", userDept=").append(userDept);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}