package com.yan.vaccine.register.mapper;

import com.yan.vaccine.register.model.VaBooking;
import com.yan.vaccine.register.model.VaBookingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaBookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    long countByExample(VaBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int deleteByExample(VaBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int deleteByPrimaryKey(String sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int insert(VaBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int insertSelective(VaBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    List<VaBooking> selectByExample(VaBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    VaBooking selectByPrimaryKey(String sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") VaBooking record, @Param("example") VaBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int updateByExample(@Param("record") VaBooking record, @Param("example") VaBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int updateByPrimaryKeySelective(VaBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    int updateByPrimaryKey(VaBooking record);
}