package com.yan.vaccine.register.mapper;

import com.yan.vaccine.register.model.VaHdcvMst;
import com.yan.vaccine.register.model.VaHdcvMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaHdcvMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    long countByExample(VaHdcvMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int deleteByExample(VaHdcvMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int deleteByPrimaryKey(String sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int insert(VaHdcvMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int insertSelective(VaHdcvMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    List<VaHdcvMst> selectByExample(VaHdcvMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    VaHdcvMst selectByPrimaryKey(String sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") VaHdcvMst record, @Param("example") VaHdcvMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int updateByExample(@Param("record") VaHdcvMst record, @Param("example") VaHdcvMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int updateByPrimaryKeySelective(VaHdcvMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    int updateByPrimaryKey(VaHdcvMst record);
}