package com.yan.vaccine.register.mapper;

import com.yan.vaccine.register.model.VaType;
import com.yan.vaccine.register.model.VaTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    long countByExample(VaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int deleteByExample(VaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int deleteByPrimaryKey(String vaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int insert(VaType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int insertSelective(VaType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    List<VaType> selectByExample(VaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    VaType selectByPrimaryKey(String vaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") VaType record, @Param("example") VaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int updateByExample(@Param("record") VaType record, @Param("example") VaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(VaType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_type
     *
     * @mbg.generated Mon Aug 06 08:49:52 CST 2018
     */
    int updateByPrimaryKey(VaType record);
}