package com.yan.vaccine.common.model;

import java.io.Serializable;

public class SysEnum extends SysEnumKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_enum.ename
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_enum.use_flag
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    private String useFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_enum.ename
     *
     * @return the value of sys_enum.ename
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_enum.ename
     *
     * @param ename the value for sys_enum.ename
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_enum.use_flag
     *
     * @return the value of sys_enum.use_flag
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    public String getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_enum.use_flag
     *
     * @param useFlag the value for sys_enum.use_flag
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag == null ? null : useFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ename=").append(ename);
        sb.append(", useFlag=").append(useFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}