package com.yan.vaccine.hosp.mapper;

import com.yan.vaccine.hosp.model.VaHosp;
import com.yan.vaccine.hosp.model.VaHospExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaHospMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    long countByExample(VaHospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int deleteByExample(VaHospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int deleteByPrimaryKey(String hospNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int insert(VaHosp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int insertSelective(VaHosp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    List<VaHosp> selectByExample(VaHospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    VaHosp selectByPrimaryKey(String hospNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") VaHosp record, @Param("example") VaHospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int updateByExample(@Param("record") VaHosp record, @Param("example") VaHospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int updateByPrimaryKeySelective(VaHosp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    int updateByPrimaryKey(VaHosp record);
}