package com.yan.vaccine.plan.model;

import java.util.ArrayList;
import java.util.List;

public class VaPlanDetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public VaPlanDetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysnoIsNull() {
            addCriterion("sysno is null");
            return (Criteria) this;
        }

        public Criteria andSysnoIsNotNull() {
            addCriterion("sysno is not null");
            return (Criteria) this;
        }

        public Criteria andSysnoEqualTo(String value) {
            addCriterion("sysno =", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotEqualTo(String value) {
            addCriterion("sysno <>", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoGreaterThan(String value) {
            addCriterion("sysno >", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoGreaterThanOrEqualTo(String value) {
            addCriterion("sysno >=", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLessThan(String value) {
            addCriterion("sysno <", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLessThanOrEqualTo(String value) {
            addCriterion("sysno <=", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLike(String value) {
            addCriterion("sysno like", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotLike(String value) {
            addCriterion("sysno not like", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoIn(List<String> values) {
            addCriterion("sysno in", values, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotIn(List<String> values) {
            addCriterion("sysno not in", values, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoBetween(String value1, String value2) {
            addCriterion("sysno between", value1, value2, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotBetween(String value1, String value2) {
            addCriterion("sysno not between", value1, value2, "sysno");
            return (Criteria) this;
        }

        public Criteria andLineNoIsNull() {
            addCriterion("line_no is null");
            return (Criteria) this;
        }

        public Criteria andLineNoIsNotNull() {
            addCriterion("line_no is not null");
            return (Criteria) this;
        }

        public Criteria andLineNoEqualTo(Integer value) {
            addCriterion("line_no =", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoNotEqualTo(Integer value) {
            addCriterion("line_no <>", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoGreaterThan(Integer value) {
            addCriterion("line_no >", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("line_no >=", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoLessThan(Integer value) {
            addCriterion("line_no <", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoLessThanOrEqualTo(Integer value) {
            addCriterion("line_no <=", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoIn(List<Integer> values) {
            addCriterion("line_no in", values, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoNotIn(List<Integer> values) {
            addCriterion("line_no not in", values, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoBetween(Integer value1, Integer value2) {
            addCriterion("line_no between", value1, value2, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoNotBetween(Integer value1, Integer value2) {
            addCriterion("line_no not between", value1, value2, "lineNo");
            return (Criteria) this;
        }

        public Criteria andVaNameIsNull() {
            addCriterion("va_name is null");
            return (Criteria) this;
        }

        public Criteria andVaNameIsNotNull() {
            addCriterion("va_name is not null");
            return (Criteria) this;
        }

        public Criteria andVaNameEqualTo(String value) {
            addCriterion("va_name =", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameNotEqualTo(String value) {
            addCriterion("va_name <>", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameGreaterThan(String value) {
            addCriterion("va_name >", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameGreaterThanOrEqualTo(String value) {
            addCriterion("va_name >=", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameLessThan(String value) {
            addCriterion("va_name <", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameLessThanOrEqualTo(String value) {
            addCriterion("va_name <=", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameLike(String value) {
            addCriterion("va_name like", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameNotLike(String value) {
            addCriterion("va_name not like", value, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameIn(List<String> values) {
            addCriterion("va_name in", values, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameNotIn(List<String> values) {
            addCriterion("va_name not in", values, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameBetween(String value1, String value2) {
            addCriterion("va_name between", value1, value2, "vaName");
            return (Criteria) this;
        }

        public Criteria andVaNameNotBetween(String value1, String value2) {
            addCriterion("va_name not between", value1, value2, "vaName");
            return (Criteria) this;
        }

        public Criteria andPlanDtIsNull() {
            addCriterion("plan_dt is null");
            return (Criteria) this;
        }

        public Criteria andPlanDtIsNotNull() {
            addCriterion("plan_dt is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDtEqualTo(String value) {
            addCriterion("plan_dt =", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtNotEqualTo(String value) {
            addCriterion("plan_dt <>", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtGreaterThan(String value) {
            addCriterion("plan_dt >", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtGreaterThanOrEqualTo(String value) {
            addCriterion("plan_dt >=", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtLessThan(String value) {
            addCriterion("plan_dt <", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtLessThanOrEqualTo(String value) {
            addCriterion("plan_dt <=", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtLike(String value) {
            addCriterion("plan_dt like", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtNotLike(String value) {
            addCriterion("plan_dt not like", value, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtIn(List<String> values) {
            addCriterion("plan_dt in", values, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtNotIn(List<String> values) {
            addCriterion("plan_dt not in", values, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtBetween(String value1, String value2) {
            addCriterion("plan_dt between", value1, value2, "planDt");
            return (Criteria) this;
        }

        public Criteria andPlanDtNotBetween(String value1, String value2) {
            addCriterion("plan_dt not between", value1, value2, "planDt");
            return (Criteria) this;
        }

        public Criteria andExecDtIsNull() {
            addCriterion("exec_dt is null");
            return (Criteria) this;
        }

        public Criteria andExecDtIsNotNull() {
            addCriterion("exec_dt is not null");
            return (Criteria) this;
        }

        public Criteria andExecDtEqualTo(String value) {
            addCriterion("exec_dt =", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtNotEqualTo(String value) {
            addCriterion("exec_dt <>", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtGreaterThan(String value) {
            addCriterion("exec_dt >", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtGreaterThanOrEqualTo(String value) {
            addCriterion("exec_dt >=", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtLessThan(String value) {
            addCriterion("exec_dt <", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtLessThanOrEqualTo(String value) {
            addCriterion("exec_dt <=", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtLike(String value) {
            addCriterion("exec_dt like", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtNotLike(String value) {
            addCriterion("exec_dt not like", value, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtIn(List<String> values) {
            addCriterion("exec_dt in", values, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtNotIn(List<String> values) {
            addCriterion("exec_dt not in", values, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtBetween(String value1, String value2) {
            addCriterion("exec_dt between", value1, value2, "execDt");
            return (Criteria) this;
        }

        public Criteria andExecDtNotBetween(String value1, String value2) {
            addCriterion("exec_dt not between", value1, value2, "execDt");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNull() {
            addCriterion("batch_no is null");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNotNull() {
            addCriterion("batch_no is not null");
            return (Criteria) this;
        }

        public Criteria andBatchNoEqualTo(String value) {
            addCriterion("batch_no =", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotEqualTo(String value) {
            addCriterion("batch_no <>", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThan(String value) {
            addCriterion("batch_no >", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThanOrEqualTo(String value) {
            addCriterion("batch_no >=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThan(String value) {
            addCriterion("batch_no <", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThanOrEqualTo(String value) {
            addCriterion("batch_no <=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLike(String value) {
            addCriterion("batch_no like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotLike(String value) {
            addCriterion("batch_no not like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoIn(List<String> values) {
            addCriterion("batch_no in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotIn(List<String> values) {
            addCriterion("batch_no not in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoBetween(String value1, String value2) {
            addCriterion("batch_no between", value1, value2, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotBetween(String value1, String value2) {
            addCriterion("batch_no not between", value1, value2, "batchNo");
            return (Criteria) this;
        }

        public Criteria andManufNoIsNull() {
            addCriterion("manuf_no is null");
            return (Criteria) this;
        }

        public Criteria andManufNoIsNotNull() {
            addCriterion("manuf_no is not null");
            return (Criteria) this;
        }

        public Criteria andManufNoEqualTo(String value) {
            addCriterion("manuf_no =", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoNotEqualTo(String value) {
            addCriterion("manuf_no <>", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoGreaterThan(String value) {
            addCriterion("manuf_no >", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoGreaterThanOrEqualTo(String value) {
            addCriterion("manuf_no >=", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoLessThan(String value) {
            addCriterion("manuf_no <", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoLessThanOrEqualTo(String value) {
            addCriterion("manuf_no <=", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoLike(String value) {
            addCriterion("manuf_no like", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoNotLike(String value) {
            addCriterion("manuf_no not like", value, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoIn(List<String> values) {
            addCriterion("manuf_no in", values, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoNotIn(List<String> values) {
            addCriterion("manuf_no not in", values, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoBetween(String value1, String value2) {
            addCriterion("manuf_no between", value1, value2, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNoNotBetween(String value1, String value2) {
            addCriterion("manuf_no not between", value1, value2, "manufNo");
            return (Criteria) this;
        }

        public Criteria andManufNameIsNull() {
            addCriterion("manuf_name is null");
            return (Criteria) this;
        }

        public Criteria andManufNameIsNotNull() {
            addCriterion("manuf_name is not null");
            return (Criteria) this;
        }

        public Criteria andManufNameEqualTo(String value) {
            addCriterion("manuf_name =", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameNotEqualTo(String value) {
            addCriterion("manuf_name <>", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameGreaterThan(String value) {
            addCriterion("manuf_name >", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameGreaterThanOrEqualTo(String value) {
            addCriterion("manuf_name >=", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameLessThan(String value) {
            addCriterion("manuf_name <", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameLessThanOrEqualTo(String value) {
            addCriterion("manuf_name <=", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameLike(String value) {
            addCriterion("manuf_name like", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameNotLike(String value) {
            addCriterion("manuf_name not like", value, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameIn(List<String> values) {
            addCriterion("manuf_name in", values, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameNotIn(List<String> values) {
            addCriterion("manuf_name not in", values, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameBetween(String value1, String value2) {
            addCriterion("manuf_name between", value1, value2, "manufName");
            return (Criteria) this;
        }

        public Criteria andManufNameNotBetween(String value1, String value2) {
            addCriterion("manuf_name not between", value1, value2, "manufName");
            return (Criteria) this;
        }

        public Criteria andVaHospIsNull() {
            addCriterion("va_hosp is null");
            return (Criteria) this;
        }

        public Criteria andVaHospIsNotNull() {
            addCriterion("va_hosp is not null");
            return (Criteria) this;
        }

        public Criteria andVaHospEqualTo(String value) {
            addCriterion("va_hosp =", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospNotEqualTo(String value) {
            addCriterion("va_hosp <>", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospGreaterThan(String value) {
            addCriterion("va_hosp >", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospGreaterThanOrEqualTo(String value) {
            addCriterion("va_hosp >=", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospLessThan(String value) {
            addCriterion("va_hosp <", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospLessThanOrEqualTo(String value) {
            addCriterion("va_hosp <=", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospLike(String value) {
            addCriterion("va_hosp like", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospNotLike(String value) {
            addCriterion("va_hosp not like", value, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospIn(List<String> values) {
            addCriterion("va_hosp in", values, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospNotIn(List<String> values) {
            addCriterion("va_hosp not in", values, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospBetween(String value1, String value2) {
            addCriterion("va_hosp between", value1, value2, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospNotBetween(String value1, String value2) {
            addCriterion("va_hosp not between", value1, value2, "vaHosp");
            return (Criteria) this;
        }

        public Criteria andVaHospnameIsNull() {
            addCriterion("va_hospname is null");
            return (Criteria) this;
        }

        public Criteria andVaHospnameIsNotNull() {
            addCriterion("va_hospname is not null");
            return (Criteria) this;
        }

        public Criteria andVaHospnameEqualTo(String value) {
            addCriterion("va_hospname =", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameNotEqualTo(String value) {
            addCriterion("va_hospname <>", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameGreaterThan(String value) {
            addCriterion("va_hospname >", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameGreaterThanOrEqualTo(String value) {
            addCriterion("va_hospname >=", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameLessThan(String value) {
            addCriterion("va_hospname <", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameLessThanOrEqualTo(String value) {
            addCriterion("va_hospname <=", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameLike(String value) {
            addCriterion("va_hospname like", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameNotLike(String value) {
            addCriterion("va_hospname not like", value, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameIn(List<String> values) {
            addCriterion("va_hospname in", values, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameNotIn(List<String> values) {
            addCriterion("va_hospname not in", values, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameBetween(String value1, String value2) {
            addCriterion("va_hospname between", value1, value2, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaHospnameNotBetween(String value1, String value2) {
            addCriterion("va_hospname not between", value1, value2, "vaHospname");
            return (Criteria) this;
        }

        public Criteria andVaOperIsNull() {
            addCriterion("va_oper is null");
            return (Criteria) this;
        }

        public Criteria andVaOperIsNotNull() {
            addCriterion("va_oper is not null");
            return (Criteria) this;
        }

        public Criteria andVaOperEqualTo(String value) {
            addCriterion("va_oper =", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperNotEqualTo(String value) {
            addCriterion("va_oper <>", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperGreaterThan(String value) {
            addCriterion("va_oper >", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperGreaterThanOrEqualTo(String value) {
            addCriterion("va_oper >=", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperLessThan(String value) {
            addCriterion("va_oper <", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperLessThanOrEqualTo(String value) {
            addCriterion("va_oper <=", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperLike(String value) {
            addCriterion("va_oper like", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperNotLike(String value) {
            addCriterion("va_oper not like", value, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperIn(List<String> values) {
            addCriterion("va_oper in", values, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperNotIn(List<String> values) {
            addCriterion("va_oper not in", values, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperBetween(String value1, String value2) {
            addCriterion("va_oper between", value1, value2, "vaOper");
            return (Criteria) this;
        }

        public Criteria andVaOperNotBetween(String value1, String value2) {
            addCriterion("va_oper not between", value1, value2, "vaOper");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeIsNull() {
            addCriterion("drug_barcode is null");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeIsNotNull() {
            addCriterion("drug_barcode is not null");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeEqualTo(String value) {
            addCriterion("drug_barcode =", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeNotEqualTo(String value) {
            addCriterion("drug_barcode <>", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeGreaterThan(String value) {
            addCriterion("drug_barcode >", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("drug_barcode >=", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeLessThan(String value) {
            addCriterion("drug_barcode <", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeLessThanOrEqualTo(String value) {
            addCriterion("drug_barcode <=", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeLike(String value) {
            addCriterion("drug_barcode like", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeNotLike(String value) {
            addCriterion("drug_barcode not like", value, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeIn(List<String> values) {
            addCriterion("drug_barcode in", values, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeNotIn(List<String> values) {
            addCriterion("drug_barcode not in", values, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeBetween(String value1, String value2) {
            addCriterion("drug_barcode between", value1, value2, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andDrugBarcodeNotBetween(String value1, String value2) {
            addCriterion("drug_barcode not between", value1, value2, "drugBarcode");
            return (Criteria) this;
        }

        public Criteria andVaLeftIsNull() {
            addCriterion("va_left is null");
            return (Criteria) this;
        }

        public Criteria andVaLeftIsNotNull() {
            addCriterion("va_left is not null");
            return (Criteria) this;
        }

        public Criteria andVaLeftEqualTo(String value) {
            addCriterion("va_left =", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftNotEqualTo(String value) {
            addCriterion("va_left <>", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftGreaterThan(String value) {
            addCriterion("va_left >", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftGreaterThanOrEqualTo(String value) {
            addCriterion("va_left >=", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftLessThan(String value) {
            addCriterion("va_left <", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftLessThanOrEqualTo(String value) {
            addCriterion("va_left <=", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftLike(String value) {
            addCriterion("va_left like", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftNotLike(String value) {
            addCriterion("va_left not like", value, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftIn(List<String> values) {
            addCriterion("va_left in", values, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftNotIn(List<String> values) {
            addCriterion("va_left not in", values, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftBetween(String value1, String value2) {
            addCriterion("va_left between", value1, value2, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andVaLeftNotBetween(String value1, String value2) {
            addCriterion("va_left not between", value1, value2, "vaLeft");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIsNull() {
            addCriterion("status_flag is null");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIsNotNull() {
            addCriterion("status_flag is not null");
            return (Criteria) this;
        }

        public Criteria andStatusFlagEqualTo(String value) {
            addCriterion("status_flag =", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotEqualTo(String value) {
            addCriterion("status_flag <>", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagGreaterThan(String value) {
            addCriterion("status_flag >", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagGreaterThanOrEqualTo(String value) {
            addCriterion("status_flag >=", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLessThan(String value) {
            addCriterion("status_flag <", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLessThanOrEqualTo(String value) {
            addCriterion("status_flag <=", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLike(String value) {
            addCriterion("status_flag like", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotLike(String value) {
            addCriterion("status_flag not like", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIn(List<String> values) {
            addCriterion("status_flag in", values, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotIn(List<String> values) {
            addCriterion("status_flag not in", values, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagBetween(String value1, String value2) {
            addCriterion("status_flag between", value1, value2, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotBetween(String value1, String value2) {
            addCriterion("status_flag not between", value1, value2, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andFeedbackIsNull() {
            addCriterion("feedback is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackIsNotNull() {
            addCriterion("feedback is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackEqualTo(String value) {
            addCriterion("feedback =", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackNotEqualTo(String value) {
            addCriterion("feedback <>", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackGreaterThan(String value) {
            addCriterion("feedback >", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackGreaterThanOrEqualTo(String value) {
            addCriterion("feedback >=", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackLessThan(String value) {
            addCriterion("feedback <", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackLessThanOrEqualTo(String value) {
            addCriterion("feedback <=", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackLike(String value) {
            addCriterion("feedback like", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackNotLike(String value) {
            addCriterion("feedback not like", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackIn(List<String> values) {
            addCriterion("feedback in", values, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackNotIn(List<String> values) {
            addCriterion("feedback not in", values, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackBetween(String value1, String value2) {
            addCriterion("feedback between", value1, value2, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackNotBetween(String value1, String value2) {
            addCriterion("feedback not between", value1, value2, "feedback");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_plan_det
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 03 14:57:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_plan_det
     *
     * @mbg.generated Fri Aug 03 14:57:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}