package com.yan.vaccine.register.model;

import java.util.ArrayList;
import java.util.List;

public class VaBookingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public VaBookingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysnoIsNull() {
            addCriterion("sysno is null");
            return (Criteria) this;
        }

        public Criteria andSysnoIsNotNull() {
            addCriterion("sysno is not null");
            return (Criteria) this;
        }

        public Criteria andSysnoEqualTo(String value) {
            addCriterion("sysno =", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotEqualTo(String value) {
            addCriterion("sysno <>", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoGreaterThan(String value) {
            addCriterion("sysno >", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoGreaterThanOrEqualTo(String value) {
            addCriterion("sysno >=", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLessThan(String value) {
            addCriterion("sysno <", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLessThanOrEqualTo(String value) {
            addCriterion("sysno <=", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLike(String value) {
            addCriterion("sysno like", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotLike(String value) {
            addCriterion("sysno not like", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoIn(List<String> values) {
            addCriterion("sysno in", values, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotIn(List<String> values) {
            addCriterion("sysno not in", values, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoBetween(String value1, String value2) {
            addCriterion("sysno between", value1, value2, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotBetween(String value1, String value2) {
            addCriterion("sysno not between", value1, value2, "sysno");
            return (Criteria) this;
        }

        public Criteria andBookDtIsNull() {
            addCriterion("book_dt is null");
            return (Criteria) this;
        }

        public Criteria andBookDtIsNotNull() {
            addCriterion("book_dt is not null");
            return (Criteria) this;
        }

        public Criteria andBookDtEqualTo(String value) {
            addCriterion("book_dt =", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtNotEqualTo(String value) {
            addCriterion("book_dt <>", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtGreaterThan(String value) {
            addCriterion("book_dt >", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtGreaterThanOrEqualTo(String value) {
            addCriterion("book_dt >=", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtLessThan(String value) {
            addCriterion("book_dt <", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtLessThanOrEqualTo(String value) {
            addCriterion("book_dt <=", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtLike(String value) {
            addCriterion("book_dt like", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtNotLike(String value) {
            addCriterion("book_dt not like", value, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtIn(List<String> values) {
            addCriterion("book_dt in", values, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtNotIn(List<String> values) {
            addCriterion("book_dt not in", values, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtBetween(String value1, String value2) {
            addCriterion("book_dt between", value1, value2, "bookDt");
            return (Criteria) this;
        }

        public Criteria andBookDtNotBetween(String value1, String value2) {
            addCriterion("book_dt not between", value1, value2, "bookDt");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("card_no is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("card_no is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("card_no =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("card_no <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("card_no >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("card_no >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("card_no <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("card_no <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("card_no like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("card_no not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("card_no in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("card_no not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("card_no between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("card_no not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardInnoIsNull() {
            addCriterion("card_inno is null");
            return (Criteria) this;
        }

        public Criteria andCardInnoIsNotNull() {
            addCriterion("card_inno is not null");
            return (Criteria) this;
        }

        public Criteria andCardInnoEqualTo(String value) {
            addCriterion("card_inno =", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoNotEqualTo(String value) {
            addCriterion("card_inno <>", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoGreaterThan(String value) {
            addCriterion("card_inno >", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoGreaterThanOrEqualTo(String value) {
            addCriterion("card_inno >=", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoLessThan(String value) {
            addCriterion("card_inno <", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoLessThanOrEqualTo(String value) {
            addCriterion("card_inno <=", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoLike(String value) {
            addCriterion("card_inno like", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoNotLike(String value) {
            addCriterion("card_inno not like", value, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoIn(List<String> values) {
            addCriterion("card_inno in", values, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoNotIn(List<String> values) {
            addCriterion("card_inno not in", values, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoBetween(String value1, String value2) {
            addCriterion("card_inno between", value1, value2, "cardInno");
            return (Criteria) this;
        }

        public Criteria andCardInnoNotBetween(String value1, String value2) {
            addCriterion("card_inno not between", value1, value2, "cardInno");
            return (Criteria) this;
        }

        public Criteria andBlhNoIsNull() {
            addCriterion("blh_no is null");
            return (Criteria) this;
        }

        public Criteria andBlhNoIsNotNull() {
            addCriterion("blh_no is not null");
            return (Criteria) this;
        }

        public Criteria andBlhNoEqualTo(String value) {
            addCriterion("blh_no =", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoNotEqualTo(String value) {
            addCriterion("blh_no <>", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoGreaterThan(String value) {
            addCriterion("blh_no >", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoGreaterThanOrEqualTo(String value) {
            addCriterion("blh_no >=", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoLessThan(String value) {
            addCriterion("blh_no <", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoLessThanOrEqualTo(String value) {
            addCriterion("blh_no <=", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoLike(String value) {
            addCriterion("blh_no like", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoNotLike(String value) {
            addCriterion("blh_no not like", value, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoIn(List<String> values) {
            addCriterion("blh_no in", values, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoNotIn(List<String> values) {
            addCriterion("blh_no not in", values, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoBetween(String value1, String value2) {
            addCriterion("blh_no between", value1, value2, "blhNo");
            return (Criteria) this;
        }

        public Criteria andBlhNoNotBetween(String value1, String value2) {
            addCriterion("blh_no not between", value1, value2, "blhNo");
            return (Criteria) this;
        }

        public Criteria andPatNameIsNull() {
            addCriterion("pat_name is null");
            return (Criteria) this;
        }

        public Criteria andPatNameIsNotNull() {
            addCriterion("pat_name is not null");
            return (Criteria) this;
        }

        public Criteria andPatNameEqualTo(String value) {
            addCriterion("pat_name =", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameNotEqualTo(String value) {
            addCriterion("pat_name <>", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameGreaterThan(String value) {
            addCriterion("pat_name >", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameGreaterThanOrEqualTo(String value) {
            addCriterion("pat_name >=", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameLessThan(String value) {
            addCriterion("pat_name <", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameLessThanOrEqualTo(String value) {
            addCriterion("pat_name <=", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameLike(String value) {
            addCriterion("pat_name like", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameNotLike(String value) {
            addCriterion("pat_name not like", value, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameIn(List<String> values) {
            addCriterion("pat_name in", values, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameNotIn(List<String> values) {
            addCriterion("pat_name not in", values, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameBetween(String value1, String value2) {
            addCriterion("pat_name between", value1, value2, "patName");
            return (Criteria) this;
        }

        public Criteria andPatNameNotBetween(String value1, String value2) {
            addCriterion("pat_name not between", value1, value2, "patName");
            return (Criteria) this;
        }

        public Criteria andPatSexIsNull() {
            addCriterion("pat_sex is null");
            return (Criteria) this;
        }

        public Criteria andPatSexIsNotNull() {
            addCriterion("pat_sex is not null");
            return (Criteria) this;
        }

        public Criteria andPatSexEqualTo(String value) {
            addCriterion("pat_sex =", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexNotEqualTo(String value) {
            addCriterion("pat_sex <>", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexGreaterThan(String value) {
            addCriterion("pat_sex >", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexGreaterThanOrEqualTo(String value) {
            addCriterion("pat_sex >=", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexLessThan(String value) {
            addCriterion("pat_sex <", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexLessThanOrEqualTo(String value) {
            addCriterion("pat_sex <=", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexLike(String value) {
            addCriterion("pat_sex like", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexNotLike(String value) {
            addCriterion("pat_sex not like", value, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexIn(List<String> values) {
            addCriterion("pat_sex in", values, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexNotIn(List<String> values) {
            addCriterion("pat_sex not in", values, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexBetween(String value1, String value2) {
            addCriterion("pat_sex between", value1, value2, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatSexNotBetween(String value1, String value2) {
            addCriterion("pat_sex not between", value1, value2, "patSex");
            return (Criteria) this;
        }

        public Criteria andPatAgeIsNull() {
            addCriterion("pat_age is null");
            return (Criteria) this;
        }

        public Criteria andPatAgeIsNotNull() {
            addCriterion("pat_age is not null");
            return (Criteria) this;
        }

        public Criteria andPatAgeEqualTo(String value) {
            addCriterion("pat_age =", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeNotEqualTo(String value) {
            addCriterion("pat_age <>", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeGreaterThan(String value) {
            addCriterion("pat_age >", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeGreaterThanOrEqualTo(String value) {
            addCriterion("pat_age >=", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeLessThan(String value) {
            addCriterion("pat_age <", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeLessThanOrEqualTo(String value) {
            addCriterion("pat_age <=", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeLike(String value) {
            addCriterion("pat_age like", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeNotLike(String value) {
            addCriterion("pat_age not like", value, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeIn(List<String> values) {
            addCriterion("pat_age in", values, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeNotIn(List<String> values) {
            addCriterion("pat_age not in", values, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeBetween(String value1, String value2) {
            addCriterion("pat_age between", value1, value2, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatAgeNotBetween(String value1, String value2) {
            addCriterion("pat_age not between", value1, value2, "patAge");
            return (Criteria) this;
        }

        public Criteria andPatOccuIsNull() {
            addCriterion("pat_occu is null");
            return (Criteria) this;
        }

        public Criteria andPatOccuIsNotNull() {
            addCriterion("pat_occu is not null");
            return (Criteria) this;
        }

        public Criteria andPatOccuEqualTo(String value) {
            addCriterion("pat_occu =", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuNotEqualTo(String value) {
            addCriterion("pat_occu <>", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuGreaterThan(String value) {
            addCriterion("pat_occu >", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuGreaterThanOrEqualTo(String value) {
            addCriterion("pat_occu >=", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuLessThan(String value) {
            addCriterion("pat_occu <", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuLessThanOrEqualTo(String value) {
            addCriterion("pat_occu <=", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuLike(String value) {
            addCriterion("pat_occu like", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuNotLike(String value) {
            addCriterion("pat_occu not like", value, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuIn(List<String> values) {
            addCriterion("pat_occu in", values, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuNotIn(List<String> values) {
            addCriterion("pat_occu not in", values, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuBetween(String value1, String value2) {
            addCriterion("pat_occu between", value1, value2, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatOccuNotBetween(String value1, String value2) {
            addCriterion("pat_occu not between", value1, value2, "patOccu");
            return (Criteria) this;
        }

        public Criteria andPatAddIsNull() {
            addCriterion("pat_add is null");
            return (Criteria) this;
        }

        public Criteria andPatAddIsNotNull() {
            addCriterion("pat_add is not null");
            return (Criteria) this;
        }

        public Criteria andPatAddEqualTo(String value) {
            addCriterion("pat_add =", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddNotEqualTo(String value) {
            addCriterion("pat_add <>", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddGreaterThan(String value) {
            addCriterion("pat_add >", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddGreaterThanOrEqualTo(String value) {
            addCriterion("pat_add >=", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddLessThan(String value) {
            addCriterion("pat_add <", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddLessThanOrEqualTo(String value) {
            addCriterion("pat_add <=", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddLike(String value) {
            addCriterion("pat_add like", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddNotLike(String value) {
            addCriterion("pat_add not like", value, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddIn(List<String> values) {
            addCriterion("pat_add in", values, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddNotIn(List<String> values) {
            addCriterion("pat_add not in", values, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddBetween(String value1, String value2) {
            addCriterion("pat_add between", value1, value2, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatAddNotBetween(String value1, String value2) {
            addCriterion("pat_add not between", value1, value2, "patAdd");
            return (Criteria) this;
        }

        public Criteria andPatTelIsNull() {
            addCriterion("pat_tel is null");
            return (Criteria) this;
        }

        public Criteria andPatTelIsNotNull() {
            addCriterion("pat_tel is not null");
            return (Criteria) this;
        }

        public Criteria andPatTelEqualTo(String value) {
            addCriterion("pat_tel =", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelNotEqualTo(String value) {
            addCriterion("pat_tel <>", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelGreaterThan(String value) {
            addCriterion("pat_tel >", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelGreaterThanOrEqualTo(String value) {
            addCriterion("pat_tel >=", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelLessThan(String value) {
            addCriterion("pat_tel <", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelLessThanOrEqualTo(String value) {
            addCriterion("pat_tel <=", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelLike(String value) {
            addCriterion("pat_tel like", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelNotLike(String value) {
            addCriterion("pat_tel not like", value, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelIn(List<String> values) {
            addCriterion("pat_tel in", values, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelNotIn(List<String> values) {
            addCriterion("pat_tel not in", values, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelBetween(String value1, String value2) {
            addCriterion("pat_tel between", value1, value2, "patTel");
            return (Criteria) this;
        }

        public Criteria andPatTelNotBetween(String value1, String value2) {
            addCriterion("pat_tel not between", value1, value2, "patTel");
            return (Criteria) this;
        }

        public Criteria andVaCodeIsNull() {
            addCriterion("va_code is null");
            return (Criteria) this;
        }

        public Criteria andVaCodeIsNotNull() {
            addCriterion("va_code is not null");
            return (Criteria) this;
        }

        public Criteria andVaCodeEqualTo(String value) {
            addCriterion("va_code =", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeNotEqualTo(String value) {
            addCriterion("va_code <>", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeGreaterThan(String value) {
            addCriterion("va_code >", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("va_code >=", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeLessThan(String value) {
            addCriterion("va_code <", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeLessThanOrEqualTo(String value) {
            addCriterion("va_code <=", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeLike(String value) {
            addCriterion("va_code like", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeNotLike(String value) {
            addCriterion("va_code not like", value, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeIn(List<String> values) {
            addCriterion("va_code in", values, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeNotIn(List<String> values) {
            addCriterion("va_code not in", values, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeBetween(String value1, String value2) {
            addCriterion("va_code between", value1, value2, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaCodeNotBetween(String value1, String value2) {
            addCriterion("va_code not between", value1, value2, "vaCode");
            return (Criteria) this;
        }

        public Criteria andVaDocIsNull() {
            addCriterion("va_doc is null");
            return (Criteria) this;
        }

        public Criteria andVaDocIsNotNull() {
            addCriterion("va_doc is not null");
            return (Criteria) this;
        }

        public Criteria andVaDocEqualTo(String value) {
            addCriterion("va_doc =", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocNotEqualTo(String value) {
            addCriterion("va_doc <>", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocGreaterThan(String value) {
            addCriterion("va_doc >", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocGreaterThanOrEqualTo(String value) {
            addCriterion("va_doc >=", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocLessThan(String value) {
            addCriterion("va_doc <", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocLessThanOrEqualTo(String value) {
            addCriterion("va_doc <=", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocLike(String value) {
            addCriterion("va_doc like", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocNotLike(String value) {
            addCriterion("va_doc not like", value, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocIn(List<String> values) {
            addCriterion("va_doc in", values, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocNotIn(List<String> values) {
            addCriterion("va_doc not in", values, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocBetween(String value1, String value2) {
            addCriterion("va_doc between", value1, value2, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andVaDocNotBetween(String value1, String value2) {
            addCriterion("va_doc not between", value1, value2, "vaDoc");
            return (Criteria) this;
        }

        public Criteria andHospNoIsNull() {
            addCriterion("hosp_no is null");
            return (Criteria) this;
        }

        public Criteria andHospNoIsNotNull() {
            addCriterion("hosp_no is not null");
            return (Criteria) this;
        }

        public Criteria andHospNoEqualTo(String value) {
            addCriterion("hosp_no =", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotEqualTo(String value) {
            addCriterion("hosp_no <>", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoGreaterThan(String value) {
            addCriterion("hosp_no >", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoGreaterThanOrEqualTo(String value) {
            addCriterion("hosp_no >=", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoLessThan(String value) {
            addCriterion("hosp_no <", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoLessThanOrEqualTo(String value) {
            addCriterion("hosp_no <=", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoLike(String value) {
            addCriterion("hosp_no like", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotLike(String value) {
            addCriterion("hosp_no not like", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoIn(List<String> values) {
            addCriterion("hosp_no in", values, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotIn(List<String> values) {
            addCriterion("hosp_no not in", values, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoBetween(String value1, String value2) {
            addCriterion("hosp_no between", value1, value2, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotBetween(String value1, String value2) {
            addCriterion("hosp_no not between", value1, value2, "hospNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_booking
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 03 14:56:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}