package com.yan.vaccine.register.model;

import java.io.Serializable;

public class VaBooking implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.sysno
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String sysno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.book_dt
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String bookDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.card_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.card_inno
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String cardInno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.blh_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String blhNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.pat_name
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String patName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.pat_sex
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String patSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.pat_age
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String patAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.pat_occu
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String patOccu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.pat_add
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String patAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.pat_tel
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String patTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.va_code
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String vaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.va_doc
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String vaDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_booking.hosp_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private String hospNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.sysno
     *
     * @return the value of va_booking.sysno
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getSysno() {
        return sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.sysno
     *
     * @param sysno the value for va_booking.sysno
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setSysno(String sysno) {
        this.sysno = sysno == null ? null : sysno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.book_dt
     *
     * @return the value of va_booking.book_dt
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getBookDt() {
        return bookDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.book_dt
     *
     * @param bookDt the value for va_booking.book_dt
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setBookDt(String bookDt) {
        this.bookDt = bookDt == null ? null : bookDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.card_no
     *
     * @return the value of va_booking.card_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.card_no
     *
     * @param cardNo the value for va_booking.card_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.card_inno
     *
     * @return the value of va_booking.card_inno
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getCardInno() {
        return cardInno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.card_inno
     *
     * @param cardInno the value for va_booking.card_inno
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setCardInno(String cardInno) {
        this.cardInno = cardInno == null ? null : cardInno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.blh_no
     *
     * @return the value of va_booking.blh_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getBlhNo() {
        return blhNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.blh_no
     *
     * @param blhNo the value for va_booking.blh_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setBlhNo(String blhNo) {
        this.blhNo = blhNo == null ? null : blhNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.pat_name
     *
     * @return the value of va_booking.pat_name
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getPatName() {
        return patName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.pat_name
     *
     * @param patName the value for va_booking.pat_name
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setPatName(String patName) {
        this.patName = patName == null ? null : patName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.pat_sex
     *
     * @return the value of va_booking.pat_sex
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getPatSex() {
        return patSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.pat_sex
     *
     * @param patSex the value for va_booking.pat_sex
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setPatSex(String patSex) {
        this.patSex = patSex == null ? null : patSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.pat_age
     *
     * @return the value of va_booking.pat_age
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getPatAge() {
        return patAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.pat_age
     *
     * @param patAge the value for va_booking.pat_age
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setPatAge(String patAge) {
        this.patAge = patAge == null ? null : patAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.pat_occu
     *
     * @return the value of va_booking.pat_occu
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getPatOccu() {
        return patOccu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.pat_occu
     *
     * @param patOccu the value for va_booking.pat_occu
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setPatOccu(String patOccu) {
        this.patOccu = patOccu == null ? null : patOccu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.pat_add
     *
     * @return the value of va_booking.pat_add
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getPatAdd() {
        return patAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.pat_add
     *
     * @param patAdd the value for va_booking.pat_add
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setPatAdd(String patAdd) {
        this.patAdd = patAdd == null ? null : patAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.pat_tel
     *
     * @return the value of va_booking.pat_tel
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getPatTel() {
        return patTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.pat_tel
     *
     * @param patTel the value for va_booking.pat_tel
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setPatTel(String patTel) {
        this.patTel = patTel == null ? null : patTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.va_code
     *
     * @return the value of va_booking.va_code
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getVaCode() {
        return vaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.va_code
     *
     * @param vaCode the value for va_booking.va_code
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setVaCode(String vaCode) {
        this.vaCode = vaCode == null ? null : vaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.va_doc
     *
     * @return the value of va_booking.va_doc
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getVaDoc() {
        return vaDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.va_doc
     *
     * @param vaDoc the value for va_booking.va_doc
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setVaDoc(String vaDoc) {
        this.vaDoc = vaDoc == null ? null : vaDoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_booking.hosp_no
     *
     * @return the value of va_booking.hosp_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public String getHospNo() {
        return hospNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_booking.hosp_no
     *
     * @param hospNo the value for va_booking.hosp_no
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    public void setHospNo(String hospNo) {
        this.hospNo = hospNo == null ? null : hospNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_booking
     *
     * @mbg.generated Fri Aug 03 14:56:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysno=").append(sysno);
        sb.append(", bookDt=").append(bookDt);
        sb.append(", cardNo=").append(cardNo);
        sb.append(", cardInno=").append(cardInno);
        sb.append(", blhNo=").append(blhNo);
        sb.append(", patName=").append(patName);
        sb.append(", patSex=").append(patSex);
        sb.append(", patAge=").append(patAge);
        sb.append(", patOccu=").append(patOccu);
        sb.append(", patAdd=").append(patAdd);
        sb.append(", patTel=").append(patTel);
        sb.append(", vaCode=").append(vaCode);
        sb.append(", vaDoc=").append(vaDoc);
        sb.append(", hospNo=").append(hospNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}