package com.yan.vaccine.register.model;

import java.io.Serializable;

public class VaHdcvMst implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.sysno
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String sysno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.hdcv_dt
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String hdcvDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.hdcv_add
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String hdcvAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.dog_type
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String dogType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.expose
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String expose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.cut_part
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String cutPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.cut_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String cutNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.cut_deal
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String cutDeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.hosp_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String hospNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.remarks
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.pat_weight
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String patWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.va_protein
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String vaProtein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.va_times
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String vaTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.va_history
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String vaHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.va_offsite
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String vaOffsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.va_sysno
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String vaSysno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.va_protein_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String vaProteinNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hdcv_mst.va_protein_part
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private String vaProteinPart;

    private String vaProteinFac;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.sysno
     *
     * @return the value of va_hdcv_mst.sysno
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getSysno() {
        return sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.sysno
     *
     * @param sysno the value for va_hdcv_mst.sysno
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setSysno(String sysno) {
        this.sysno = sysno == null ? null : sysno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.hdcv_dt
     *
     * @return the value of va_hdcv_mst.hdcv_dt
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getHdcvDt() {
        return hdcvDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.hdcv_dt
     *
     * @param hdcvDt the value for va_hdcv_mst.hdcv_dt
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setHdcvDt(String hdcvDt) {
        this.hdcvDt = hdcvDt == null ? null : hdcvDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.hdcv_add
     *
     * @return the value of va_hdcv_mst.hdcv_add
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getHdcvAdd() {
        return hdcvAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.hdcv_add
     *
     * @param hdcvAdd the value for va_hdcv_mst.hdcv_add
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setHdcvAdd(String hdcvAdd) {
        this.hdcvAdd = hdcvAdd == null ? null : hdcvAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.dog_type
     *
     * @return the value of va_hdcv_mst.dog_type
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getDogType() {
        return dogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.dog_type
     *
     * @param dogType the value for va_hdcv_mst.dog_type
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setDogType(String dogType) {
        this.dogType = dogType == null ? null : dogType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.expose
     *
     * @return the value of va_hdcv_mst.expose
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getExpose() {
        return expose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.expose
     *
     * @param expose the value for va_hdcv_mst.expose
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setExpose(String expose) {
        this.expose = expose == null ? null : expose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.cut_part
     *
     * @return the value of va_hdcv_mst.cut_part
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getCutPart() {
        return cutPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.cut_part
     *
     * @param cutPart the value for va_hdcv_mst.cut_part
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setCutPart(String cutPart) {
        this.cutPart = cutPart == null ? null : cutPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.cut_no
     *
     * @return the value of va_hdcv_mst.cut_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getCutNo() {
        return cutNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.cut_no
     *
     * @param cutNo the value for va_hdcv_mst.cut_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setCutNo(String cutNo) {
        this.cutNo = cutNo == null ? null : cutNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.cut_deal
     *
     * @return the value of va_hdcv_mst.cut_deal
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getCutDeal() {
        return cutDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.cut_deal
     *
     * @param cutDeal the value for va_hdcv_mst.cut_deal
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setCutDeal(String cutDeal) {
        this.cutDeal = cutDeal == null ? null : cutDeal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.hosp_no
     *
     * @return the value of va_hdcv_mst.hosp_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getHospNo() {
        return hospNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.hosp_no
     *
     * @param hospNo the value for va_hdcv_mst.hosp_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setHospNo(String hospNo) {
        this.hospNo = hospNo == null ? null : hospNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.remarks
     *
     * @return the value of va_hdcv_mst.remarks
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.remarks
     *
     * @param remarks the value for va_hdcv_mst.remarks
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.pat_weight
     *
     * @return the value of va_hdcv_mst.pat_weight
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getPatWeight() {
        return patWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.pat_weight
     *
     * @param patWeight the value for va_hdcv_mst.pat_weight
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setPatWeight(String patWeight) {
        this.patWeight = patWeight == null ? null : patWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.va_protein
     *
     * @return the value of va_hdcv_mst.va_protein
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getVaProtein() {
        return vaProtein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.va_protein
     *
     * @param vaProtein the value for va_hdcv_mst.va_protein
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setVaProtein(String vaProtein) {
        this.vaProtein = vaProtein == null ? null : vaProtein.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.va_times
     *
     * @return the value of va_hdcv_mst.va_times
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getVaTimes() {
        return vaTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.va_times
     *
     * @param vaTimes the value for va_hdcv_mst.va_times
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setVaTimes(String vaTimes) {
        this.vaTimes = vaTimes == null ? null : vaTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.va_history
     *
     * @return the value of va_hdcv_mst.va_history
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getVaHistory() {
        return vaHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.va_history
     *
     * @param vaHistory the value for va_hdcv_mst.va_history
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setVaHistory(String vaHistory) {
        this.vaHistory = vaHistory == null ? null : vaHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.va_offsite
     *
     * @return the value of va_hdcv_mst.va_offsite
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getVaOffsite() {
        return vaOffsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.va_offsite
     *
     * @param vaOffsite the value for va_hdcv_mst.va_offsite
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setVaOffsite(String vaOffsite) {
        this.vaOffsite = vaOffsite == null ? null : vaOffsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.va_sysno
     *
     * @return the value of va_hdcv_mst.va_sysno
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getVaSysno() {
        return vaSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.va_sysno
     *
     * @param vaSysno the value for va_hdcv_mst.va_sysno
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setVaSysno(String vaSysno) {
        this.vaSysno = vaSysno == null ? null : vaSysno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.va_protein_no
     *
     * @return the value of va_hdcv_mst.va_protein_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getVaProteinNo() {
        return vaProteinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.va_protein_no
     *
     * @param vaProteinNo the value for va_hdcv_mst.va_protein_no
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setVaProteinNo(String vaProteinNo) {
        this.vaProteinNo = vaProteinNo == null ? null : vaProteinNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hdcv_mst.va_protein_part
     *
     * @return the value of va_hdcv_mst.va_protein_part
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getVaProteinPart() {
        return vaProteinPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hdcv_mst.va_protein_part
     *
     * @param vaProteinPart the value for va_hdcv_mst.va_protein_part
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setVaProteinPart(String vaProteinPart) {
        this.vaProteinPart = vaProteinPart == null ? null : vaProteinPart.trim();
    }


    public String getVaProteinFac() {
        return vaProteinFac;
    }

    public void setVaProteinFac(String vaProteinFac) {
        this.vaProteinFac = vaProteinFac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysno=").append(sysno);
        sb.append(", hdcvDt=").append(hdcvDt);
        sb.append(", hdcvAdd=").append(hdcvAdd);
        sb.append(", dogType=").append(dogType);
        sb.append(", expose=").append(expose);
        sb.append(", cutPart=").append(cutPart);
        sb.append(", cutNo=").append(cutNo);
        sb.append(", cutDeal=").append(cutDeal);
        sb.append(", hospNo=").append(hospNo);
        sb.append(", remarks=").append(remarks);
        sb.append(", patWeight=").append(patWeight);
        sb.append(", vaProtein=").append(vaProtein);
        sb.append(", vaTimes=").append(vaTimes);
        sb.append(", vaHistory=").append(vaHistory);
        sb.append(", vaOffsite=").append(vaOffsite);
        sb.append(", vaSysno=").append(vaSysno);
        sb.append(", vaProteinNo=").append(vaProteinNo);
        sb.append(", vaProteinPart=").append(vaProteinPart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}