package com.yan.vaccine.register.model;

import java.util.ArrayList;
import java.util.List;

public class VaHdcvMstExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public VaHdcvMstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysnoIsNull() {
            addCriterion("sysno is null");
            return (Criteria) this;
        }

        public Criteria andSysnoIsNotNull() {
            addCriterion("sysno is not null");
            return (Criteria) this;
        }

        public Criteria andSysnoEqualTo(String value) {
            addCriterion("sysno =", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotEqualTo(String value) {
            addCriterion("sysno <>", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoGreaterThan(String value) {
            addCriterion("sysno >", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoGreaterThanOrEqualTo(String value) {
            addCriterion("sysno >=", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLessThan(String value) {
            addCriterion("sysno <", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLessThanOrEqualTo(String value) {
            addCriterion("sysno <=", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoLike(String value) {
            addCriterion("sysno like", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotLike(String value) {
            addCriterion("sysno not like", value, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoIn(List<String> values) {
            addCriterion("sysno in", values, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotIn(List<String> values) {
            addCriterion("sysno not in", values, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoBetween(String value1, String value2) {
            addCriterion("sysno between", value1, value2, "sysno");
            return (Criteria) this;
        }

        public Criteria andSysnoNotBetween(String value1, String value2) {
            addCriterion("sysno not between", value1, value2, "sysno");
            return (Criteria) this;
        }

        public Criteria andHdcvDtIsNull() {
            addCriterion("hdcv_dt is null");
            return (Criteria) this;
        }

        public Criteria andHdcvDtIsNotNull() {
            addCriterion("hdcv_dt is not null");
            return (Criteria) this;
        }

        public Criteria andHdcvDtEqualTo(String value) {
            addCriterion("hdcv_dt =", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtNotEqualTo(String value) {
            addCriterion("hdcv_dt <>", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtGreaterThan(String value) {
            addCriterion("hdcv_dt >", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtGreaterThanOrEqualTo(String value) {
            addCriterion("hdcv_dt >=", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtLessThan(String value) {
            addCriterion("hdcv_dt <", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtLessThanOrEqualTo(String value) {
            addCriterion("hdcv_dt <=", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtLike(String value) {
            addCriterion("hdcv_dt like", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtNotLike(String value) {
            addCriterion("hdcv_dt not like", value, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtIn(List<String> values) {
            addCriterion("hdcv_dt in", values, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtNotIn(List<String> values) {
            addCriterion("hdcv_dt not in", values, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtBetween(String value1, String value2) {
            addCriterion("hdcv_dt between", value1, value2, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvDtNotBetween(String value1, String value2) {
            addCriterion("hdcv_dt not between", value1, value2, "hdcvDt");
            return (Criteria) this;
        }

        public Criteria andHdcvAddIsNull() {
            addCriterion("hdcv_add is null");
            return (Criteria) this;
        }

        public Criteria andHdcvAddIsNotNull() {
            addCriterion("hdcv_add is not null");
            return (Criteria) this;
        }

        public Criteria andHdcvAddEqualTo(String value) {
            addCriterion("hdcv_add =", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddNotEqualTo(String value) {
            addCriterion("hdcv_add <>", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddGreaterThan(String value) {
            addCriterion("hdcv_add >", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddGreaterThanOrEqualTo(String value) {
            addCriterion("hdcv_add >=", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddLessThan(String value) {
            addCriterion("hdcv_add <", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddLessThanOrEqualTo(String value) {
            addCriterion("hdcv_add <=", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddLike(String value) {
            addCriterion("hdcv_add like", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddNotLike(String value) {
            addCriterion("hdcv_add not like", value, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddIn(List<String> values) {
            addCriterion("hdcv_add in", values, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddNotIn(List<String> values) {
            addCriterion("hdcv_add not in", values, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddBetween(String value1, String value2) {
            addCriterion("hdcv_add between", value1, value2, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andHdcvAddNotBetween(String value1, String value2) {
            addCriterion("hdcv_add not between", value1, value2, "hdcvAdd");
            return (Criteria) this;
        }

        public Criteria andDogTypeIsNull() {
            addCriterion("dog_type is null");
            return (Criteria) this;
        }

        public Criteria andDogTypeIsNotNull() {
            addCriterion("dog_type is not null");
            return (Criteria) this;
        }

        public Criteria andDogTypeEqualTo(String value) {
            addCriterion("dog_type =", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeNotEqualTo(String value) {
            addCriterion("dog_type <>", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeGreaterThan(String value) {
            addCriterion("dog_type >", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeGreaterThanOrEqualTo(String value) {
            addCriterion("dog_type >=", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeLessThan(String value) {
            addCriterion("dog_type <", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeLessThanOrEqualTo(String value) {
            addCriterion("dog_type <=", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeLike(String value) {
            addCriterion("dog_type like", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeNotLike(String value) {
            addCriterion("dog_type not like", value, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeIn(List<String> values) {
            addCriterion("dog_type in", values, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeNotIn(List<String> values) {
            addCriterion("dog_type not in", values, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeBetween(String value1, String value2) {
            addCriterion("dog_type between", value1, value2, "dogType");
            return (Criteria) this;
        }

        public Criteria andDogTypeNotBetween(String value1, String value2) {
            addCriterion("dog_type not between", value1, value2, "dogType");
            return (Criteria) this;
        }

        public Criteria andExposeIsNull() {
            addCriterion("expose is null");
            return (Criteria) this;
        }

        public Criteria andExposeIsNotNull() {
            addCriterion("expose is not null");
            return (Criteria) this;
        }

        public Criteria andExposeEqualTo(String value) {
            addCriterion("expose =", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeNotEqualTo(String value) {
            addCriterion("expose <>", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeGreaterThan(String value) {
            addCriterion("expose >", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeGreaterThanOrEqualTo(String value) {
            addCriterion("expose >=", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeLessThan(String value) {
            addCriterion("expose <", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeLessThanOrEqualTo(String value) {
            addCriterion("expose <=", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeLike(String value) {
            addCriterion("expose like", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeNotLike(String value) {
            addCriterion("expose not like", value, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeIn(List<String> values) {
            addCriterion("expose in", values, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeNotIn(List<String> values) {
            addCriterion("expose not in", values, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeBetween(String value1, String value2) {
            addCriterion("expose between", value1, value2, "expose");
            return (Criteria) this;
        }

        public Criteria andExposeNotBetween(String value1, String value2) {
            addCriterion("expose not between", value1, value2, "expose");
            return (Criteria) this;
        }

        public Criteria andCutPartIsNull() {
            addCriterion("cut_part is null");
            return (Criteria) this;
        }

        public Criteria andCutPartIsNotNull() {
            addCriterion("cut_part is not null");
            return (Criteria) this;
        }

        public Criteria andCutPartEqualTo(String value) {
            addCriterion("cut_part =", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartNotEqualTo(String value) {
            addCriterion("cut_part <>", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartGreaterThan(String value) {
            addCriterion("cut_part >", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartGreaterThanOrEqualTo(String value) {
            addCriterion("cut_part >=", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartLessThan(String value) {
            addCriterion("cut_part <", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartLessThanOrEqualTo(String value) {
            addCriterion("cut_part <=", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartLike(String value) {
            addCriterion("cut_part like", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartNotLike(String value) {
            addCriterion("cut_part not like", value, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartIn(List<String> values) {
            addCriterion("cut_part in", values, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartNotIn(List<String> values) {
            addCriterion("cut_part not in", values, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartBetween(String value1, String value2) {
            addCriterion("cut_part between", value1, value2, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutPartNotBetween(String value1, String value2) {
            addCriterion("cut_part not between", value1, value2, "cutPart");
            return (Criteria) this;
        }

        public Criteria andCutNoIsNull() {
            addCriterion("cut_no is null");
            return (Criteria) this;
        }

        public Criteria andCutNoIsNotNull() {
            addCriterion("cut_no is not null");
            return (Criteria) this;
        }

        public Criteria andCutNoEqualTo(String value) {
            addCriterion("cut_no =", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoNotEqualTo(String value) {
            addCriterion("cut_no <>", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoGreaterThan(String value) {
            addCriterion("cut_no >", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoGreaterThanOrEqualTo(String value) {
            addCriterion("cut_no >=", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoLessThan(String value) {
            addCriterion("cut_no <", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoLessThanOrEqualTo(String value) {
            addCriterion("cut_no <=", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoLike(String value) {
            addCriterion("cut_no like", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoNotLike(String value) {
            addCriterion("cut_no not like", value, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoIn(List<String> values) {
            addCriterion("cut_no in", values, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoNotIn(List<String> values) {
            addCriterion("cut_no not in", values, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoBetween(String value1, String value2) {
            addCriterion("cut_no between", value1, value2, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutNoNotBetween(String value1, String value2) {
            addCriterion("cut_no not between", value1, value2, "cutNo");
            return (Criteria) this;
        }

        public Criteria andCutDealIsNull() {
            addCriterion("cut_deal is null");
            return (Criteria) this;
        }

        public Criteria andCutDealIsNotNull() {
            addCriterion("cut_deal is not null");
            return (Criteria) this;
        }

        public Criteria andCutDealEqualTo(String value) {
            addCriterion("cut_deal =", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealNotEqualTo(String value) {
            addCriterion("cut_deal <>", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealGreaterThan(String value) {
            addCriterion("cut_deal >", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealGreaterThanOrEqualTo(String value) {
            addCriterion("cut_deal >=", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealLessThan(String value) {
            addCriterion("cut_deal <", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealLessThanOrEqualTo(String value) {
            addCriterion("cut_deal <=", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealLike(String value) {
            addCriterion("cut_deal like", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealNotLike(String value) {
            addCriterion("cut_deal not like", value, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealIn(List<String> values) {
            addCriterion("cut_deal in", values, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealNotIn(List<String> values) {
            addCriterion("cut_deal not in", values, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealBetween(String value1, String value2) {
            addCriterion("cut_deal between", value1, value2, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andCutDealNotBetween(String value1, String value2) {
            addCriterion("cut_deal not between", value1, value2, "cutDeal");
            return (Criteria) this;
        }

        public Criteria andHospNoIsNull() {
            addCriterion("hosp_no is null");
            return (Criteria) this;
        }

        public Criteria andHospNoIsNotNull() {
            addCriterion("hosp_no is not null");
            return (Criteria) this;
        }

        public Criteria andHospNoEqualTo(String value) {
            addCriterion("hosp_no =", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotEqualTo(String value) {
            addCriterion("hosp_no <>", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoGreaterThan(String value) {
            addCriterion("hosp_no >", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoGreaterThanOrEqualTo(String value) {
            addCriterion("hosp_no >=", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoLessThan(String value) {
            addCriterion("hosp_no <", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoLessThanOrEqualTo(String value) {
            addCriterion("hosp_no <=", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoLike(String value) {
            addCriterion("hosp_no like", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotLike(String value) {
            addCriterion("hosp_no not like", value, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoIn(List<String> values) {
            addCriterion("hosp_no in", values, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotIn(List<String> values) {
            addCriterion("hosp_no not in", values, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoBetween(String value1, String value2) {
            addCriterion("hosp_no between", value1, value2, "hospNo");
            return (Criteria) this;
        }

        public Criteria andHospNoNotBetween(String value1, String value2) {
            addCriterion("hosp_no not between", value1, value2, "hospNo");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andPatWeightIsNull() {
            addCriterion("pat_weight is null");
            return (Criteria) this;
        }

        public Criteria andPatWeightIsNotNull() {
            addCriterion("pat_weight is not null");
            return (Criteria) this;
        }

        public Criteria andPatWeightEqualTo(String value) {
            addCriterion("pat_weight =", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightNotEqualTo(String value) {
            addCriterion("pat_weight <>", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightGreaterThan(String value) {
            addCriterion("pat_weight >", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightGreaterThanOrEqualTo(String value) {
            addCriterion("pat_weight >=", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightLessThan(String value) {
            addCriterion("pat_weight <", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightLessThanOrEqualTo(String value) {
            addCriterion("pat_weight <=", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightLike(String value) {
            addCriterion("pat_weight like", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightNotLike(String value) {
            addCriterion("pat_weight not like", value, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightIn(List<String> values) {
            addCriterion("pat_weight in", values, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightNotIn(List<String> values) {
            addCriterion("pat_weight not in", values, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightBetween(String value1, String value2) {
            addCriterion("pat_weight between", value1, value2, "patWeight");
            return (Criteria) this;
        }

        public Criteria andPatWeightNotBetween(String value1, String value2) {
            addCriterion("pat_weight not between", value1, value2, "patWeight");
            return (Criteria) this;
        }

        public Criteria andVaProteinIsNull() {
            addCriterion("va_protein is null");
            return (Criteria) this;
        }

        public Criteria andVaProteinIsNotNull() {
            addCriterion("va_protein is not null");
            return (Criteria) this;
        }

        public Criteria andVaProteinEqualTo(String value) {
            addCriterion("va_protein =", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinNotEqualTo(String value) {
            addCriterion("va_protein <>", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinGreaterThan(String value) {
            addCriterion("va_protein >", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinGreaterThanOrEqualTo(String value) {
            addCriterion("va_protein >=", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinLessThan(String value) {
            addCriterion("va_protein <", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinLessThanOrEqualTo(String value) {
            addCriterion("va_protein <=", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinLike(String value) {
            addCriterion("va_protein like", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinNotLike(String value) {
            addCriterion("va_protein not like", value, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinIn(List<String> values) {
            addCriterion("va_protein in", values, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinNotIn(List<String> values) {
            addCriterion("va_protein not in", values, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinBetween(String value1, String value2) {
            addCriterion("va_protein between", value1, value2, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaProteinNotBetween(String value1, String value2) {
            addCriterion("va_protein not between", value1, value2, "vaProtein");
            return (Criteria) this;
        }

        public Criteria andVaTimesIsNull() {
            addCriterion("va_times is null");
            return (Criteria) this;
        }

        public Criteria andVaTimesIsNotNull() {
            addCriterion("va_times is not null");
            return (Criteria) this;
        }

        public Criteria andVaTimesEqualTo(String value) {
            addCriterion("va_times =", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesNotEqualTo(String value) {
            addCriterion("va_times <>", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesGreaterThan(String value) {
            addCriterion("va_times >", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesGreaterThanOrEqualTo(String value) {
            addCriterion("va_times >=", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesLessThan(String value) {
            addCriterion("va_times <", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesLessThanOrEqualTo(String value) {
            addCriterion("va_times <=", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesLike(String value) {
            addCriterion("va_times like", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesNotLike(String value) {
            addCriterion("va_times not like", value, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesIn(List<String> values) {
            addCriterion("va_times in", values, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesNotIn(List<String> values) {
            addCriterion("va_times not in", values, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesBetween(String value1, String value2) {
            addCriterion("va_times between", value1, value2, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaTimesNotBetween(String value1, String value2) {
            addCriterion("va_times not between", value1, value2, "vaTimes");
            return (Criteria) this;
        }

        public Criteria andVaHistoryIsNull() {
            addCriterion("va_history is null");
            return (Criteria) this;
        }

        public Criteria andVaHistoryIsNotNull() {
            addCriterion("va_history is not null");
            return (Criteria) this;
        }

        public Criteria andVaHistoryEqualTo(String value) {
            addCriterion("va_history =", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryNotEqualTo(String value) {
            addCriterion("va_history <>", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryGreaterThan(String value) {
            addCriterion("va_history >", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("va_history >=", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryLessThan(String value) {
            addCriterion("va_history <", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryLessThanOrEqualTo(String value) {
            addCriterion("va_history <=", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryLike(String value) {
            addCriterion("va_history like", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryNotLike(String value) {
            addCriterion("va_history not like", value, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryIn(List<String> values) {
            addCriterion("va_history in", values, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryNotIn(List<String> values) {
            addCriterion("va_history not in", values, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryBetween(String value1, String value2) {
            addCriterion("va_history between", value1, value2, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaHistoryNotBetween(String value1, String value2) {
            addCriterion("va_history not between", value1, value2, "vaHistory");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteIsNull() {
            addCriterion("va_offsite is null");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteIsNotNull() {
            addCriterion("va_offsite is not null");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteEqualTo(String value) {
            addCriterion("va_offsite =", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteNotEqualTo(String value) {
            addCriterion("va_offsite <>", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteGreaterThan(String value) {
            addCriterion("va_offsite >", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteGreaterThanOrEqualTo(String value) {
            addCriterion("va_offsite >=", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteLessThan(String value) {
            addCriterion("va_offsite <", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteLessThanOrEqualTo(String value) {
            addCriterion("va_offsite <=", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteLike(String value) {
            addCriterion("va_offsite like", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteNotLike(String value) {
            addCriterion("va_offsite not like", value, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteIn(List<String> values) {
            addCriterion("va_offsite in", values, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteNotIn(List<String> values) {
            addCriterion("va_offsite not in", values, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteBetween(String value1, String value2) {
            addCriterion("va_offsite between", value1, value2, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaOffsiteNotBetween(String value1, String value2) {
            addCriterion("va_offsite not between", value1, value2, "vaOffsite");
            return (Criteria) this;
        }

        public Criteria andVaSysnoIsNull() {
            addCriterion("va_sysno is null");
            return (Criteria) this;
        }

        public Criteria andVaSysnoIsNotNull() {
            addCriterion("va_sysno is not null");
            return (Criteria) this;
        }

        public Criteria andVaSysnoEqualTo(String value) {
            addCriterion("va_sysno =", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoNotEqualTo(String value) {
            addCriterion("va_sysno <>", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoGreaterThan(String value) {
            addCriterion("va_sysno >", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoGreaterThanOrEqualTo(String value) {
            addCriterion("va_sysno >=", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoLessThan(String value) {
            addCriterion("va_sysno <", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoLessThanOrEqualTo(String value) {
            addCriterion("va_sysno <=", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoLike(String value) {
            addCriterion("va_sysno like", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoNotLike(String value) {
            addCriterion("va_sysno not like", value, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoIn(List<String> values) {
            addCriterion("va_sysno in", values, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoNotIn(List<String> values) {
            addCriterion("va_sysno not in", values, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoBetween(String value1, String value2) {
            addCriterion("va_sysno between", value1, value2, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaSysnoNotBetween(String value1, String value2) {
            addCriterion("va_sysno not between", value1, value2, "vaSysno");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoIsNull() {
            addCriterion("va_protein_no is null");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoIsNotNull() {
            addCriterion("va_protein_no is not null");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoEqualTo(String value) {
            addCriterion("va_protein_no =", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoNotEqualTo(String value) {
            addCriterion("va_protein_no <>", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoGreaterThan(String value) {
            addCriterion("va_protein_no >", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoGreaterThanOrEqualTo(String value) {
            addCriterion("va_protein_no >=", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoLessThan(String value) {
            addCriterion("va_protein_no <", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoLessThanOrEqualTo(String value) {
            addCriterion("va_protein_no <=", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoLike(String value) {
            addCriterion("va_protein_no like", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoNotLike(String value) {
            addCriterion("va_protein_no not like", value, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoIn(List<String> values) {
            addCriterion("va_protein_no in", values, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoNotIn(List<String> values) {
            addCriterion("va_protein_no not in", values, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoBetween(String value1, String value2) {
            addCriterion("va_protein_no between", value1, value2, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinNoNotBetween(String value1, String value2) {
            addCriterion("va_protein_no not between", value1, value2, "vaProteinNo");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartIsNull() {
            addCriterion("va_protein_part is null");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartIsNotNull() {
            addCriterion("va_protein_part is not null");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartEqualTo(String value) {
            addCriterion("va_protein_part =", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartNotEqualTo(String value) {
            addCriterion("va_protein_part <>", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartGreaterThan(String value) {
            addCriterion("va_protein_part >", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartGreaterThanOrEqualTo(String value) {
            addCriterion("va_protein_part >=", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartLessThan(String value) {
            addCriterion("va_protein_part <", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartLessThanOrEqualTo(String value) {
            addCriterion("va_protein_part <=", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartLike(String value) {
            addCriterion("va_protein_part like", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartNotLike(String value) {
            addCriterion("va_protein_part not like", value, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartIn(List<String> values) {
            addCriterion("va_protein_part in", values, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartNotIn(List<String> values) {
            addCriterion("va_protein_part not in", values, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartBetween(String value1, String value2) {
            addCriterion("va_protein_part between", value1, value2, "vaProteinPart");
            return (Criteria) this;
        }

        public Criteria andVaProteinPartNotBetween(String value1, String value2) {
            addCriterion("va_protein_part not between", value1, value2, "vaProteinPart");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 19 16:58:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table va_hdcv_mst
     *
     * @mbg.generated Fri Oct 19 16:58:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}