package com.yan.vaccine.common.mapper;

import com.yan.vaccine.common.model.SysEnum;
import com.yan.vaccine.common.model.SysEnumExample;
import com.yan.vaccine.common.model.SysEnumKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysEnumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    long countByExample(SysEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int deleteByExample(SysEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int deleteByPrimaryKey(SysEnumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int insert(SysEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int insertSelective(SysEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    List<SysEnum> selectByExample(SysEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    SysEnum selectByPrimaryKey(SysEnumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysEnum record, @Param("example") SysEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int updateByExample(@Param("record") SysEnum record, @Param("example") SysEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int updateByPrimaryKeySelective(SysEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enum
     *
     * @mbg.generated Mon Aug 06 11:04:27 CST 2018
     */
    int updateByPrimaryKey(SysEnum record);
}