package com.yan.vaccine.hosp.model;

import java.io.Serializable;

public class VaHosp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hosp.hosp_no
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    private String hospNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hosp.hosp_name
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    private String hospName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hosp.pre_ip
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    private String preIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column va_hosp.status_flag
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    private String statusFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hosp.hosp_no
     *
     * @return the value of va_hosp.hosp_no
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public String getHospNo() {
        return hospNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hosp.hosp_no
     *
     * @param hospNo the value for va_hosp.hosp_no
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public void setHospNo(String hospNo) {
        this.hospNo = hospNo == null ? null : hospNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hosp.hosp_name
     *
     * @return the value of va_hosp.hosp_name
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public String getHospName() {
        return hospName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hosp.hosp_name
     *
     * @param hospName the value for va_hosp.hosp_name
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public void setHospName(String hospName) {
        this.hospName = hospName == null ? null : hospName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hosp.pre_ip
     *
     * @return the value of va_hosp.pre_ip
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public String getPreIp() {
        return preIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hosp.pre_ip
     *
     * @param preIp the value for va_hosp.pre_ip
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public void setPreIp(String preIp) {
        this.preIp = preIp == null ? null : preIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column va_hosp.status_flag
     *
     * @return the value of va_hosp.status_flag
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column va_hosp.status_flag
     *
     * @param statusFlag the value for va_hosp.status_flag
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag == null ? null : statusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_hosp
     *
     * @mbg.generated Tue Aug 14 09:02:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hospNo=").append(hospNo);
        sb.append(", hospName=").append(hospName);
        sb.append(", preIp=").append(preIp);
        sb.append(", statusFlag=").append(statusFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}